### ISSUE TITLE
enigmampc/secret-network-sw-dev docker image results in "SIGILL: illegal instruction" on startup on Ubuntu 20.04.

### ISSUE THREAD

**Issue by theonekeyg** [scrtlabs/SecretNetwork#763] opened 2021-06-28 17:02 UTC
I'm getting this error every time i try to start enigmampc/secret-network-sw-dev docker image on Ubuntu 20.04. I tried to replicate similar error on couple of other images, but this happens only with enigmampc/secret-network-sw-dev.

I tried running it on my other Debian 10 machine, which worked just fine.

I'm using docker 20.10.7, i tried downgrading to 20.10.6, which is the version i have installed on my Debian machine, but that didn't help.

I understand that the issue probably lies in my local docker installation (or some shared dependency), but since so far i failed to replicate it on any other image besides enigmampc/secret-network-sw-dev and i ran out of ideas to fix it, i thought this is ok if i ask here for help. Did someone experienced similar issues? Do you have any ideas of what could cause this error and how would i fix it?

Full error log: https://gist.github.com/theonekeyg/bbe322e07782020577177daaa0ab766a
OS: Ubuntu 20.04
Docker version: 20.10.7 | 20.10.6

**Comment by assafmo** [comment] 2021-06-28 19:01
Hi :wave: 
What version of enigmampc/secret-network-sw-dev are you using?

**Comment by theonekeyg** [comment] 2021-06-28 19:38
Hi @assafmo, i'm using the latest version of enigmampc/secret-network-sw-dev from docker hub.

**Comment by reuvenpo** [comment] 2021-06-29 13:42
The issue is usually because you tried running it on an older CPU. We just had another user report this issue a couple days ago, running on a 10-year-old intel CPU.
The reason for this is that we compile the local testnet [assuming users use 6th gen "skylake" CPUs and above](https://github.com/enigmampc/SecretNetwork/blob/master/cosmwasm/packages/wasmi-runtime/Makefile#L97) because that's when SGX support was originally added.
I wonder if compiling it with lower architecture assumptions would still allow running the nodes in simulation mode.

**Comment by Cashmaney** [comment] 2021-06-29 16:03
@theonekeyg I compiled and uploaded a version that might work for you - `enigmampc/secret-network-sw-dev:test` can you try it and let me know if it solves your problem?

**Comment by theonekeyg** [comment] 2021-06-29 17:22
@Cashmaney Yes, your version works just fine, thanks a lot.

It looks like @reuvenpo is right, and it is absence of sgx support on my ubuntu machine that was causing the error. I checked specs of my debian machine's cpu and it indeed had sgx support.

Do you think that would be reasonable to have separate tag like `enigmampc/secret-network-sw-dev:nosgx` on dockerhub for older cpus?

**Comment by reuvenpo** [comment] 2021-06-29 18:12
The local testnet already doesn't require SGX, but i was wondering is _some_ special CPI support was required even for running the application in simulation mode. So I'm happy that wasn't the case! 😄 
The reason that flag was there, was because telling the compiler it can expect some minimum CPU version allows it to generate faster code, which is useful for node runners and validators. It just carried over to the local testnet version as well.

**Comment by assafmo** [comment] 2022-04-03 11:31
Resolved by https://github.com/scrtlabs/SecretNetwork/commit/5405c63a9d1dafa7ff47cb9da69330006f9df7df, should already be fixed on any version after [v1.0.5](https://hub.docker.com/r/enigmampc/secret-network-sw-dev/tags).

**Closed by assafmo** 2022-04-03 11:31 UTC
Labels: good first issue, help wanted
